### ISSUE TITLE
Throw forbidden exceptions

### ISSUE THREAD

**Issue by pmatatias** [dart-actions/tweet#1]
I already setup the secret repository
![image](https://github.com/dart-actions/tweet/assets/33835308/f7ad0907-a30e-442a-bef6-c66f56436cea)

---

I try both way options:

- with `consumer-key` setup

this is my `.yml` file :
```
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-actions/tweet@v1.0.1
        with:
          text: "CK Line repo updated!"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
```

and i got this result:

```
Error: TwitterException: No response data exists for the request.

  ✅ Status Code:
   403

  ✅ Request:
   POST https://api.twitter.com/2/tweets?

  ✅ Headers:
   {x-transaction-id: 44480c4d18d94d5f, cache-control: no-cache, no-store, max-age=0, set-cookie: guest_id_marketing=v1%3A169355796843857137; Max-Age=63072000; Expires=Sun, 31 Aug 2025 08:46:08 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None,guest_id_ads=v1%3A169355796843857137; Max-Age=63072000; Expires=Sun, 31 Aug 2025 08:46:08 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None,personalization_id="v1_f5acnjueoyEo04pzeB9Ovw=="; Max-Age=63072000; Expires=Sun, 31 Aug 2025 08:46:08 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None,guest_id=v1%3A169355796843857137; Max-Age=63072000; Expires=Sun, 31 Aug 2025 08:46:08 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None, x-rate-limit-limit: 40000, date: Fri, 01 Sep 2023 08:46:08 UTC, api-version: 2.66, content-encoding: gzip, strict-transport-security: max-age=63[11](https://github.com/pmatatias/ck-linecode/actions/runs/6047371164/job/16410687873#step:3:12)38519, x-rate-limit-remaining: 39999, perf: 7626143928, content-type: application/json; charset=utf-8, x-xss-protection: 0, server: tsa_b, x-access-level: read, content-disposition: attachment; filename=json.json, x-response-time: [12](https://github.com/pmatatias/ck-linecode/actions/runs/6047371164/job/16410687873#step:3:13), content-length: 176, x-connection-hash: 7681e06972598a1[15](https://github.com/pmatatias/ck-linecode/actions/runs/6047371164/job/16410687873#step:3:16)45eb2d496a9726f4778583128e99eb4b329aa360b31f4a4, x-frame-options: SAMEORIGIN, x-content-type-options: nosniff, x-rate-limit-reset: [16](https://github.com/pmatatias/ck-linecode/actions/runs/6047371164/job/16410687873#step:3:17)93558868}

  ✅ Body:
   {"title":"Forbidden","status":403,"detail":"Your client app is not configured with the appropriate oauth1 app permissions for this endpoint.","type":"https://api.twitter.com/2/problems/oauth1-permissions"}

  Please create an Issue if you have a question or suggestion for this exception.
```

---

then i try with second options

- with `OAuth2.0` 

```
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-actions/tweet@v1.0.1
        with:
          text: "CK Line repo updated!"
          bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
```

i got this result

```
Unhandled exception:
Invalid argument(s): An access token using OAuth 2.0 or OAuth 1.0a is required.
#0      new _TwitterApi (package:twitter_api_v2/src/twitter_api.dart:204)
#1      new TwitterApi (package:twitter_api_v2/src/twitter_api.dart:13[9](https://github.com/pmatatias/ck-linecode/actions/runs/6047143475/job/16410027202#step:3:10))
#2      tweet (package:tweet/tweet.dart:[11](https://github.com/pmatatias/ck-linecode/actions/runs/6047143475/job/16410027202#step:3:12))
#3      main (file:///app/bin/server.dart:8)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

---

### Is there additional setup that i need to do?

TIA
